# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed
#--------------------------

title: T1m3-m4ch1n3

tagline: Revese Engineering and Malware Analysis

description: >-
  A place where you can find Reversing Engineering CTF challenges writeups,
  Malware Analysis reports and some low-level geeky stuff

url: 'https://T1m3M.me'

author: Abdelrahman Nasr

avatar: /assets/img/sample/avatar.png

github:
  username: T1m3M

twitter:
  username: T1m3M

social:
  name: Abdelrahman Nasr
  email: 1.h4ck.t1m3@gmail.com
  links:
    - https://twitter.com/T1m3M
    - https://github.com/T1m3M

google_site_verification: 8KurBy7FwofXMvxhSjeTiiwavWCbfv_GmzQqxD_6OHU

#--------------------------

baseurl: ''

timezone: Africa/Cairo

google_analytics:
  id: 'G-1WZELSLYX1'
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false

disqus:
  comments: false
  shortname: ''


theme_mode: dark

toc: true

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /posts/:title/

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: index.html
    values:
      breadcrumb:
        -
          label: Posts
  -
    scope:
      path: tags
    values:
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      dynamic_title: true
      breadcrumb:
        -
          label: Home
          url: /

sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
